version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    environment:
      - NODE_ENV=development
      - PORT=4500
      - MONGO_URI=${MONGO_URI:-mongodb+srv://your_atlas_connection_string}
      - CLIENT_ORIGIN=http://localhost:3000
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_for_development_only}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - LOGDNA_KEY=${LOGDNA_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4500/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: ./chat
      dockerfile: Dockerfile
      target: build # Use the build stage for development
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4500
      - REACT_APP_SOCKET_URL=http://localhost:4500
    volumes:
      - ./chat:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start
    restart: unless-stopped
